### ISSUE TITLE
Dropzone upload field doesn´t appear

### ISSUE THREAD

**Issue by insideth** [hypeJunction/hypeDropzone#5]
Ismayil, when I enable the plugin and I try to upload a file from /file/add, the standad file upload field is displayed instead of the dropzone one, must I do somenting more?

Tested in Elgg 2.2.1 clean installation

**Comment by hypeJunction** [comment]
Did you download from the 'Releases' tab?

**Comment by insideth** [comment]
I cloned it from Git and performed a composer update

**Comment by hypeJunction** [comment]
Oh, just reread your question. This plugin doesn't replace the default file upload form. Read the readme.

**Comment by insideth** [comment]
With previous releases of the plugin the default upload form was replaced, can you tell me which code or view must I add to this release if possible?

**Comment by hypeJunction** [comment]
It was never there, because it doesn't make sense to integrate it with the file plugin form.

**Comment by insideth** [comment]
Okk thanks Ismayil, maybe I´m confused with other plugins with file upload function.
