### ISSUE TITLE
package bower-asset/dropzone could not be found

### ISSUE THREAD

**Issue by nachopavon** [hypeJunction/hypeDropzone#6]
When installing with composer from master I get this message:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/dropzone could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by hypeJunction** [comment]
Install composer asset plugin
https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md
