### ISSUE TITLE
on click does not open image folder?

### ISSUE THREAD

**Issue by rayhill75** [hypeJunction/hypeDropzone#7]
Hi, another issue. Photo upload now in activity feed.

When click on photo icon 'drag&drop' opens.

click on drag&drop, nothing happens?
![drops](https://cloud.githubusercontent.com/assets/26484231/24051061/c8d35fa6-0b28-11e7-98a2-28b43fa7c300.png)
![drop1](https://cloud.githubusercontent.com/assets/26484231/24051060/c8ce4d86-0b28-11e7-92f3-5d031e676f30.png)

**Comment by hypeJunction** [comment]
What's in your browser console? Any errors?

**Comment by rayhill75** [comment]
browser console on drag&drop screen
![browse](https://cloud.githubusercontent.com/assets/26484231/24051412/ea702026-0b29-11e7-8d3a-92c16baa5c13.png)

**Comment by hypeJunction** [comment]
Something is up with your cache. Try flushing. Try to access the JS URL directly and trace your server error logs.
